In [1]:
#Se cargan las librerias
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

In [2]:
#Se lee el archivo y se le asigna la variable df9
df9 = pd.read_csv('vid18_180219.dat', skiprows=1, sep=',',header=None,names=["TIMESTAMP","RECORD","batt_volt_Min","logger_temp","short_up_Avg","short_dn_Avg","long_up_Avg","long_dn_Avg","cnr4_T_C_Avg","cnr4_T_K_Avg","long_up_corr_Avg","long_dn_corr_Avg","Rs_net_Avg","Rl_net_Avg","albedo_Avg","Rn_Avg","AirTC_Avg","RH","WS_ms_S_WVT","WindDir_D1_WVT","WindDir_SD1_WVT","Temp_C_Avg(1)","Temp_C_Avg(2)","Temp_C_Avg(3)","Temp_C_Avg(4)","Result1_Avg","Result2_Avg","Result3_Avg","Result4_Avg","Result5_Avg","Result6_Avg","Result7_Avg","Result8_Avg","Result9_Avg","Riego_mm_Tot","Perco_mm_Tot"])

#Se transforma nuestra columna TIMESTAMP que representa el tiempo en datetime
df9['TIMESTAMP'] = pd.to_datetime(df9.apply(lambda x: x['TIMESTAMP'], 1), dayfirst=True)
df9 = pd.DataFrame(df9)

#Solo nos interesan 2 columnas  TIMESTAMP (Fecha) y  AirTC_Avg (Temperatura del aire, ºC).
df9.dtypes 
df9 = df9[['TIMESTAMP','AirTC_Avg']]

#Creamos una columna para los días, años, meses y horas
df9['MES'] = df9['TIMESTAMP'].dt.month
df9['AÑO'] = df9['TIMESTAMP'].dt.year
df9['DIA'] = df9['TIMESTAMP'].dt.day
df9['HORA'] = df9['TIMESTAMP'].dt.hour

#Sacamos la temperatura media por hora que es con la que vamos a trabajar 
dfmedia = df9.set_index('TIMESTAMP').resample('H').mean()

In [3]:
#Se agarran los valores desde noviembre hasta el ultimo dato
dfmedia = dfmedia.loc['2018-11-01 00:00:00':'2019-02-18 07:30:00']

In [4]:
conditions = [
    (dfmedia['AirTC_Avg'] >= 1.5) & (dfmedia['AirTC_Avg'] <= 2.4),
    (dfmedia['AirTC_Avg'] >= 2.5) & (dfmedia['AirTC_Avg'] <= 9.1),
    (dfmedia['AirTC_Avg'] >= 9.2) & (dfmedia['AirTC_Avg'] <= 12.4),
    (dfmedia['AirTC_Avg'] >= 12.5) & (dfmedia['AirTC_Avg'] <= 15.9),
    (dfmedia['AirTC_Avg'] >= 16) & (dfmedia['AirTC_Avg'] <=18),
    (dfmedia['AirTC_Avg'] > 18 )]

choices = [0.5, 1.0, 0.5, 0, -0.5, -1.0]

dfmedia['UF'] = np.select(conditions, choices, default=0)

dfmedia['UF24'] = dfmedia.groupby(['AÑO','MES','DIA'])['UF'].transform('sum')

In [5]:
df10 = dfmedia[['AirTC_Avg']]

In [6]:
df10 = df10.resample('D').sum()

In [8]:
df10 ['UF'] = dfmedia['UF24']



dfmedia ['TMAX'] = df9.set_index('TIMESTAMP').resample('D')["AirTC_Avg"].max()

In [11]:
dfmedia

                     AirTC_Avg   MES     AÑO   DIA  HORA   UF  UF24    TMAX
TIMESTAMP
2018-11-01 00:00:00   8.708333  11.0  2018.0   1.0   0.0  1.0  -0.5  29.580
2018-11-01 01:00:00   8.493333  11.0  2018.0   1.0   1.0  1.0  -0.5     NaN
2018-11-01 02:00:00   8.690000  11.0  2018.0   1.0   2.0  1.0  -0.5     NaN
2018-11-01 03:00:00   8.846667  11.0  2018.0   1.0   3.0  1.0  -0.5     NaN
2018-11-01 04:00:00   7.397500  11.0  2018.0   1.0   4.0  1.0  -0.5     NaN
2018-11-01 05:00:00   7.289833  11.0  2018.0   1.0   5.0  1.0  -0.5     NaN
2018-11-01 06:00:00   6.806833  11.0  2018.0   1.0   6.0  1.0  -0.5     NaN
2018-11-01 07:00:00   8.110167  11.0  2018.0   1.0   7.0  1.0  -0.5     NaN
2018-11-01 08:00:00  14.960000  11.0  2018.0   1.0   8.0  0.0  -0.5     NaN
2018-11-01 09:00:00  19.710000  11.0  2018.0   1.0   9.0 -1.0  -0.5     NaN
2018-11-01 10:00:00  22.396667  11.0  2018.0   1.0  10.0 -1.0  -0.5     NaN
2018-11-01 11:00:00  23.853333  11.0  2018.0   1.0  11.0 -1.0  -0.5     NaN
2018-11-01 12:00:00  25.125000  11.0  2018.0   1.0  12.0 -1.0  -0.5     NaN
2018-11-01 13:00:00  26.520000  11.0  2018.0   1.0  13.0 -1.0  -0.5     NaN
2018-11-01 14:00:00  27.380000  11.0  2018.0   1.0  14.0 -1.0  -0.5     NaN
2018-11-01 15:00:00  28.160000  11.0  2018.0   1.0  15.0 -1.0  -0.5     NaN
2018-11-01 16:00:00  28.621667  11.0  2018.0   1.0  16.0 -1.0  -0.5     NaN
2018-11-01 17:00:00  27.438333  11.0  2018.0   1.0  17.0 -1.0  -0.5     NaN
2018-11-01 18:00:00  16.916667  11.0  2018.0   1.0  18.0 -0.5  -0.5     NaN
2018-11-01 19:00:00  14.708333  11.0  2018.0   1.0  19.0  0.0  -0.5     NaN
2018-11-01 20:00:00  14.060000  11.0  2018.0   1.0  20.0  0.0  -0.5     NaN
2018-11-01 21:00:00  13.010000  11.0  2018.0   1.0  21.0  0.0  -0.5     NaN
2018-11-01 22:00:00  12.291667  11.0  2018.0   1.0  22.0  0.5  -0.5     NaN
2018-11-01 23:00:00  10.970000  11.0  2018.0   1.0  23.0  0.5  -0.5     NaN
2018-11-02 00:00:00  10.556667  11.0  2018.0   2.0   0.0  0.5  -9.0  31.350
2018-11-02 01:00:00  10.248333  11.0  2018.0   2.0   1.0  0.5  -9.0     NaN
2018-11-02 02:00:00  10.498333  11.0  2018.0   2.0   2.0  0.5  -9.0     NaN
2018-11-02 03:00:00  11.653333  11.0  2018.0   2.0   3.0  0.5  -9.0     NaN
2018-11-02 04:00:00  12.081667  11.0  2018.0   2.0   4.0  0.5  -9.0     NaN
2018-11-02 05:00:00  12.060000  11.0  2018.0   2.0   5.0  0.5  -9.0     NaN
...                        ...   ...     ...   ...   ...  ...   ...     ...
2019-02-17 02:00:00   6.665500   2.0  2019.0  17.0   2.0  1.0   2.5     NaN
2019-02-17 03:00:00   5.132333   2.0  2019.0  17.0   3.0  1.0   2.5     NaN
2019-02-17 04:00:00   4.533667   2.0  2019.0  17.0   4.0  1.0   2.5     NaN
2019-02-17 05:00:00   4.613000   2.0  2019.0  17.0   5.0  1.0   2.5     NaN
2019-02-17 06:00:00   4.103500   2.0  2019.0  17.0   6.0  1.0   2.5     NaN
2019-02-17 07:00:00   3.756833   2.0  2019.0  17.0   7.0  1.0   2.5     NaN
2019-02-17 08:00:00   9.520167   2.0  2019.0  17.0   8.0  0.5   2.5     NaN
2019-02-17 09:00:00  14.001667   2.0  2019.0  17.0   9.0  0.0   2.5     NaN
2019-02-17 10:00:00  17.100000   2.0  2019.0  17.0  10.0 -0.5   2.5     NaN
2019-02-17 11:00:00  18.585000   2.0  2019.0  17.0  11.0 -1.0   2.5     NaN
2019-02-17 12:00:00  19.195000   2.0  2019.0  17.0  12.0 -1.0   2.5     NaN
2019-02-17 13:00:00  19.400000   2.0  2019.0  17.0  13.0 -1.0   2.5     NaN
2019-02-17 14:00:00  20.386667   2.0  2019.0  17.0  14.0 -1.0   2.5     NaN
2019-02-17 15:00:00  20.845000   2.0  2019.0  17.0  15.0 -1.0   2.5     NaN
2019-02-17 16:00:00  20.533333   2.0  2019.0  17.0  16.0 -1.0   2.5     NaN
2019-02-17 17:00:00  20.065000   2.0  2019.0  17.0  17.0 -1.0   2.5     NaN
2019-02-17 18:00:00  18.021667   2.0  2019.0  17.0  18.0 -1.0   2.5     NaN
2019-02-17 19:00:00  15.321667   2.0  2019.0  17.0  19.0  0.0   2.5     NaN
2019-02-17 20:00:00  12.143333   2.0  2019.0  17.0  20.0  0.5   2.5     NaN
2019-02-17 21:00:00  10.508333   2.0  2019.0  17.0  21.0  0.5   2.5     NaN
2019-02-17 22:00:00   8.463333   2.0  2019.0  17.0  22.0  1.0   2.5     NaN
2019-02-17 23:00:00   7.385667   2.0  2019.0  17.0  23.0  1.0   2.5     NaN
2019-02-18 00:00:00   6.758167   2.0  2019.0  18.0   0.0  1.0   8.0   7.028
2019-02-18 01:00:00   5.966333   2.0  2019.0  18.0   1.0  1.0   8.0     NaN
2019-02-18 02:00:00   5.617833   2.0  2019.0  18.0   2.0  1.0   8.0     NaN
2019-02-18 03:00:00   5.426667   2.0  2019.0  18.0   3.0  1.0   8.0     NaN
2019-02-18 04:00:00   4.739833   2.0  2019.0  18.0   4.0  1.0   8.0     NaN
2019-02-18 05:00:00   4.157333   2.0  2019.0  18.0   5.0  1.0   8.0     NaN
2019-02-18 06:00:00   3.746500   2.0  2019.0  18.0   6.0  1.0   8.0     NaN
2019-02-18 07:00:00   3.418500   2.0  2019.0  18.0   7.0  1.0   8.0     NaN

[2624 rows x 8 columns]

In [ ]:
dfmedia